# Generated by Django 3.1.1 on 2020-10-03 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('criado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=40)),
                ('localidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=2)),
                ('criado', models.DateField(auto_now_add=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.contato')),
            ],
        ),
    ]
